#! /bin/bash

target zlib
zlib () {
  uncompress "$ZLIB_URL" "$BUILD/zlib"

  cd "$BUILD/zlib"
  ./configure --static

  replace Makefile '^CFLAGS[ ]*=' '\s-O\d*(?!\S)' ' -O2 '
  replace Makefile '^CFLAGS[ ]*=' '\s-g\s'

  make CC="${CC}" || exit 1

  addlibrary libz.a
  addheader zconf.h zlib.h
}
