# Makefile

all: hello bottlesample cherrypysample

cherrypysample:
	pyload --include bottle --include cherrypy -s cherrypysample.py

bottlesample:
	pyload --include bottle -s bottlesample.py

hello:
	pyload -s hello.py

# vim:ft=make
