#!/bin/bash
# configure tools to compile here, thiss section will change between
# different architectures.
export PATCH="patch -t"
export CC="${ARCH}-gcc -static -fno-stack-protector"
export CXX="${ARCH}-g++"
export CFLAGS="-static -fno-stack-protector"
export AR="${ARCH}-ar"
export RANLIB="${ARCH}-ranlib"
export LD="${ARCH}-ld"
export LDFLAGS=""
export STRIP="${ARCH}-strip -s"
export MKDIR="mkdir -p"

MODULES="sqlite3 ncurses openssl greenlet"

# configure dependencies
UCLIBC_VER="0.9.30.1"
UCLIBC_URL="http://www.uclibc.org/downloads/binaries/${UCLIBC_VER}/cross-compiler-${ARCH}.tar.bz2"

PYTHON_VER="3.5.0"
PYTHON_URL="https://www.python.org/ftp/python/${PYTHON_VER}/Python-${PYTHON_VER}.tar.xz"

GREENLET_VER="0.4.9"
GREENLET_URL="https://pypi.python.org/packages/source/g/greenlet/greenlet-${GREENLET_VER}.tar.gz"

OPENSSL_VER="1.0.2d"
OPENSSL_URL="ftp://ftp.openssl.org/source/openssl-${OPENSSL_VER}.tar.gz"

LIBEVENT_VER="2.0.22"
LIBEVENT_URL="https://github.com/libevent/libevent/releases/download/release-${LIBEVENT_VER}-stable/libevent-${LIBEVENT_VER}-stable.tar.gz"

BZIP2_VER="1.0.6"
BZIP2_URL="http://www.bzip.org/${BZIP2_VER}/bzip2-${BZIP2_VER}.tar.gz"

READLINE_VER="6.3"
READLINE_URL="ftp://ftp.cwru.edu/pub/bash/readline-${READLINE_VER}.tar.gz"

NCURSES_VER="6.0"
NCURSES_URL="ftp://ftp.gnu.org/gnu/ncurses/ncurses-${NCURSES_VER}.tar.gz"

ZLIB_VER="1.2.8"
ZLIB_URL="http://zlib.net/zlib-${ZLIB_VER}.tar.gz"

SQLITE3_VER="3090100"
SQLITE3_URL="https://www.sqlite.org/2015/sqlite-autoconf-${SQLITE3_VER}.tar.gz"

ADVZIP_VER="1.15"
ADVZIP_URL="http://netix.dl.sourceforge.net/project/advancemame/advancecomp/${ADVZIP_VER}/advancecomp-${ADVZIP_VER}.tar.gz"

# configure internal directories
LIBRARY_DIR="${BUILD}/_objects"
INCLUDE_DIR="${BUILD}/_include"

export CFLAGS="${CFLAGS} -I${INCLUDE_DIR}"
export LDFLAGS="${LDFLAGS} -L${LIBRARY_DIR}"

# load dependency targets
source ./targets/toolchain
source ./targets/readline
source ./targets/ncurses
source ./targets/bzip2
source ./targets/zlib
source ./targets/sqlite3
source ./targets/greenlet
source ./targets/openssl
source ./targets/libevent
source ./targets/pyload

# build targets
target main: toolchain pyload python
main () {
  cp ${BUILD}/python/pyload ${HERE}/pyload
  cp ${BUILD}/python/python ${HERE}/python
  cp ${BUILD}/python/xlib.zip ${HERE}/xlib.zip
  cat ${HERE}/xlib.zip >> ${HERE}/python
}

clean () {
  rm -f $HERE/pyload $HERE/xlib.zip $HERE/python
}
