# Dockerfile
# ajdiaz, 2015-10-22 21:58
#
# This Dockerfile create a minimal python image for docker with a simple
# python interpreter. You can create your own python application from this
# container

FROM scratch
COPY ./python /python
CMD /python

# vim:ft=dockerfile
